name: Run Analyzer

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          echo "Calling API..."
          curl -i https://rai-content-engine.vercel.app/api/analyze